# Generated by Django 4.1 on 2023-09-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasy_name', models.CharField(max_length=128, verbose_name='Nome Fantasia')),
                ('corporate_reason', models.CharField(max_length=128, verbose_name='Razao Social')),
                ('cnpj', models.CharField(max_length=128, verbose_name='CNPJ')),
                ('address', models.CharField(max_length=128, verbose_name='Nome Fantasia')),
                ('telephone', models.CharField(max_length=128, verbose_name='Nome Fantasia')),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=10)),
                ('is_main', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='AddressSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('complement', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('is_main', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliers')),
            ],
        ),
    ]
