# Generated by Django 4.1 on 2023-09-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='telephone',
        ),
    ]
