# Generated by Django 4.1 on 2023-09-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productssuppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productssuppliers',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='productssuppliers',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='productssuppliers',
            name='unit_measure',
        ),
        migrations.AddField(
            model_name='productssuppliers',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=11, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
